extras:
  healthchecks: &healthchecks
    hooks:
      failure:
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup failed for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/0ae12711-519f-484f-b5ba-eef6fe5c5e49/fail'
      success:
        - 'curl -m 10 --retry 5 -X POST -H "Content-Type: text/plain" --data "Backup successful for location: ${AUTORESTIC_LOCATION}" https://hc-ping.com/0ae12711-519f-484f-b5ba-eef6fe5c5e49'

backends:
  garage:
    type: s3
    path: http://192.168.178.105:3900/dokploy-backup/restic
    key: TYAKOuvtCccE2U5KBXg58g5F7Ss07MaQJIEl9LAPWL96fTOhNPfzebeNjtexfsyggS9V42yoc266XUU0XQ
    requirekey: false
    env: {}
    rest:
      user: ""
      password: ""
    options: {}
global:
  forget:
    keep-daily: 7
    keep-weekly: 4
locations:
  audiobooks:
    <<: *healthchecks  
    from:
    - /source/home/audiobookshelf
    type: ""
    to:
    - garage
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: 0 4 * * 0
    options: {}
    copyoption: {}
  backups:
    <<: *healthchecks    
    from:
    - /source/backups
    type: ""
    to:
    - garage
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: 0 2 * * *
    options: {}
    copyoption: {}
  dokploy:
    <<: *healthchecks    
    from:
    - /source/dokploy
    type: ""
    to:
    - garage
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: 0 3 * * *
    options: {}
    copyoption: {}
  home:
    <<: *healthchecks    
    from:
    - /source/home
    type: ""
    to:
    - garage
    hooks:
      dir: ""
      prevalidate: []
      before: []
      after: []
      success: []
      failure: []
    cron: 0 3 * * *
    options:
      backup:
        exclude:
        - /source/home/audiobookshelf/**
    copyoption: {}
version: 2
